name: tcd-prg
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.4
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - h5py
  - pyyaml
  - hydra-core
  - scikit-learn
  - tqdm
  - pandas
  - matplotlib
  - pytest
  - psutil
  - addict
  - einops
  - timm
  - ninja
  - pyg>=2.6
  - pytorch-scatter
  - pip
  - pip:
      - ruff>=0.6
      - spconv-cu118==2.3.6
